/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as LiveFlightRouteImport } from './routes/live-flight'
import { Route as LoginRouteImport } from './routes/login'
import { Route as MissionPlannerRouteImport } from './routes/mission-planner'
import { Route as SensorsRouteImport } from './routes/sensors'
import { Route as SprayControlRouteImport } from './routes/spray-control'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const LiveFlightRoute = LiveFlightRouteImport.update({
  id: '/live-flight',
  path: '/live-flight',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const MissionPlannerRoute = MissionPlannerRouteImport.update({
  id: '/mission-planner',
  path: '/mission-planner',
  getParentRoute: () => rootRouteImport,
} as any)
const SensorsRoute = SensorsRouteImport.update({
  id: '/sensors',
  path: '/sensors',
  getParentRoute: () => rootRouteImport,
} as any)
const SprayControlRoute = SprayControlRouteImport.update({
  id: '/spray-control',
  path: '/spray-control',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/live-flight': typeof LiveFlightRoute
  '/login': typeof LoginRoute
  '/mission-planner': typeof MissionPlannerRoute
  '/sensors': typeof SensorsRoute
  '/spray-control': typeof SprayControlRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/live-flight': typeof LiveFlightRoute
  '/login': typeof LoginRoute
  '/mission-planner': typeof MissionPlannerRoute
  '/sensors': typeof SensorsRoute
  '/spray-control': typeof SprayControlRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/live-flight': typeof LiveFlightRoute
  '/login': typeof LoginRoute
  '/mission-planner': typeof MissionPlannerRoute
  '/sensors': typeof SensorsRoute
  '/spray-control': typeof SprayControlRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/live-flight'
    | '/login'
    | '/mission-planner'
    | '/sensors'
    | '/spray-control'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/live-flight'
    | '/login'
    | '/mission-planner'
    | '/sensors'
    | '/spray-control'
  id:
    | '__root__'
    | '/'
    | '/live-flight'
    | '/login'
    | '/mission-planner'
    | '/sensors'
    | '/spray-control'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  LiveFlightRoute: typeof LiveFlightRoute
  LoginRoute: typeof LoginRoute
  MissionPlannerRoute: typeof MissionPlannerRoute
  SensorsRoute: typeof SensorsRoute
  SprayControlRoute: typeof SprayControlRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/live-flight': {
      id: '/live-flight'
      path: '/live-flight'
      fullPath: '/live-flight'
      preLoaderRoute: typeof LiveFlightRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/mission-planner': {
      id: '/mission-planner'
      path: '/mission-planner'
      fullPath: '/mission-planner'
      preLoaderRoute: typeof MissionPlannerRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sensors': {
      id: '/sensors'
      path: '/sensors'
      fullPath: '/sensors'
      preLoaderRoute: typeof SensorsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/spray-control': {
      id: '/spray-control'
      path: '/spray-control'
      fullPath: '/spray-control'
      preLoaderRoute: typeof SprayControlRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  LiveFlightRoute: LiveFlightRoute,
  LoginRoute: LoginRoute,
  MissionPlannerRoute: MissionPlannerRoute,
  SensorsRoute: SensorsRoute,
  SprayControlRoute: SprayControlRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
